server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_quickstart?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver